# Generated by Django 4.2 on 2023-06-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('middlename', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('age', models.BigIntegerField()),
                ('gender', models.CharField(max_length=255)),
                ('birthdate', models.BigIntegerField()),
                ('birthplace', models.CharField(max_length=255)),
                ('civilstatus', models.CharField(max_length=255)),
                ('bloodtype', models.CharField(max_length=255)),
                ('religion', models.CharField(max_length=255)),
                ('totalhouseholdmember', models.BigIntegerField()),
                ('occupation', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('educationalattainment', models.CharField(max_length=255)),
                ('householdno', models.BigIntegerField()),
            ],
        ),
    ]
