# Generated by Django 4.2 on 2023-06-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residents',
            name='birthdate',
            field=models.DateField(),
        ),
    ]
